// Code generated by gomapper; DO NOT EDIT.

package basic

import "github.com/KARTIKrocks/mapper"

func init() {
	mapper.Register(func(src User) UserDTO {
		return UserDTO{
			ID:   src.ID,
			Name: src.Name,
			Age:  int64(src.Age),
		}
	})
}
