package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var binaryPath string

func TestMain(m *testing.M) {
	os.Exit(testMain(m))
}

func testMain(m *testing.M) int {
	// Build the binary once for all integration tests.
	tmp, err := os.MkdirTemp("", "gomapper-test-*")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(tmp)

	binaryPath = filepath.Join(tmp, "gomapper")
	build := exec.Command("go", "build", "-o", binaryPath, ".")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		panic("failed to build gomapper: " + err.Error())
	}

	return m.Run()
}

// runGomapper executes the gomapper binary in the given directory with the given flags.
// It returns stdout, stderr, and any error.
func runGomapper(t *testing.T, dir string, args ...string) (string, string, error) {
	t.Helper()
	cmd := exec.Command(binaryPath, args...)
	cmd.Dir = dir
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	return stdout.String(), stderr.String(), err
}

// readGenerated reads the generated file from the given directory.
func readGenerated(t *testing.T, dir, filename string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, filename))
	if err != nil {
		t.Fatalf("reading generated file: %v", err)
	}
	return string(data)
}

// assertCompiles runs `go build` in the given directory to verify generated code compiles.
func assertCompiles(t *testing.T, dir string) {
	t.Helper()
	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated code does not compile:\n%s", out)
	}
}

// cleanGenerated removes a generated file, ignoring errors.
func cleanGenerated(dir, filename string) {
	os.Remove(filepath.Join(dir, filename))
}

// containsNormalized checks if s contains substr after collapsing runs of whitespace
// to single spaces. This handles gofmt alignment differences.
func containsNormalized(s, substr string) bool {
	normalize := func(in string) string {
		var b strings.Builder
		inSpace := false
		for _, r := range in {
			if r == ' ' || r == '\t' {
				if !inSpace {
					b.WriteByte(' ')
					inSpace = true
				}
			} else {
				b.WriteRune(r)
				inSpace = false
			}
		}
		return b.String()
	}
	return strings.Contains(normalize(s), normalize(substr))
}

func testdataDir(name string) string {
	wd, _ := os.Getwd()
	return filepath.Join(wd, "testdata", name)
}

func TestIntegration_BasicRegisterMode(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-mode", "register", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Verify key parts of the generated code.
	for _, want := range []string{
		"// Code generated by gomapper; DO NOT EDIT.",
		"package basic",
		`import "github.com/KARTIKrocks/mapper"`,
		"mapper.Register(func(src User) UserDTO {",
		"ID:   src.ID,",
		"Name: src.Name,",
		"Age:  int64(src.Age),",
	} {
		if !strings.Contains(gen, want) {
			t.Errorf("generated code missing %q", want)
		}
	}

	// Email should NOT appear (not in UserDTO).
	if strings.Contains(gen, "Email") {
		t.Error("generated code should not contain Email")
	}

	assertCompiles(t, dir)
}

func TestIntegration_FuncModeDefault(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_func_gen.go"
	defer cleanGenerated(dir, out)

	// Default mode is now func — no -mode flag needed.
	_, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	if !strings.Contains(gen, "func MapUserToUserDTO(src User) UserDTO {") {
		t.Error("missing named function")
	}
	if strings.Contains(gen, "mapper.Register") {
		t.Error("func mode should not contain mapper.Register")
	}
	if strings.Contains(gen, `import "github.com/KARTIKrocks/mapper"`) {
		t.Error("func mode should not import mapper")
	}

	assertCompiles(t, dir)
}

func TestIntegration_BothMode(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_both_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-mode", "both", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	if !strings.Contains(gen, "func MapUserToUserDTO(src User) UserDTO {") {
		t.Error("missing named function")
	}
	if !strings.Contains(gen, "mapper.Register(MapUserToUserDTO)") {
		t.Error("missing register call referencing named function")
	}

	assertCompiles(t, dir)
}

func TestIntegration_Bidirectional(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_bidi_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-bidirectional", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Default mode is func — generates named functions.
	if !strings.Contains(gen, "func MapUserToUserDTO(src User) UserDTO {") {
		t.Error("missing forward mapping User→UserDTO")
	}
	if !strings.Contains(gen, "func MapUserDTOToUser(src UserDTO) User {") {
		t.Error("missing reverse mapping UserDTO→User")
	}
	// Reverse should have TODO for unmapped Email.
	if !strings.Contains(gen, "// TODO: unmapped field Email") {
		t.Error("reverse mapping should have TODO for unmapped Email")
	}

	assertCompiles(t, dir)
}

func TestIntegration_Pairs(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_pairs_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-pairs", "User:UserDTO,TaggedSource:TaggedDest", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Default mode is func — generates named functions.
	if !strings.Contains(gen, "func MapUserToUserDTO(src User) UserDTO {") {
		t.Error("missing User→UserDTO mapping")
	}
	if !strings.Contains(gen, "func MapTaggedSourceToTaggedDest(src TaggedSource) TaggedDest {") {
		t.Error("missing TaggedSource→TaggedDest mapping")
	}

	assertCompiles(t, dir)
}

func TestIntegration_SrcTagMapping(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_tag_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "TaggedSource", "-dst", "TaggedDest", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// TaggedSource.FullName has map:"Name" tag → should map to TaggedDest.Name.
	// gofmt may align with extra spaces, so normalize whitespace.
	if !containsNormalized(gen, "Name: src.FullName,") {
		t.Errorf("expected tag-based mapping FullName→Name, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_DstTagNestedPath(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_nested_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "Person", "-dst", "PersonFlat", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// PersonFlat.Street has map:"Address.Street" → should use src.Address.Street.
	// gofmt may align with extra spaces, so normalize whitespace.
	if !containsNormalized(gen, "Street: src.Address.Street,") {
		t.Errorf("expected nested path mapping, got:\n%s", gen)
	}
	if !containsNormalized(gen, "City: src.Address.City,") {
		t.Errorf("expected nested path mapping for City, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_EmbeddedStructPromotedFields(t *testing.T) {
	dir := testdataDir("embedded")
	out := "mapper_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// ID is promoted from Base — accessor should be Base.ID.
	if !strings.Contains(gen, "ID:   src.Base.ID,") {
		t.Errorf("expected promoted field accessor src.Base.ID, got:\n%s", gen)
	}
	if !strings.Contains(gen, "Name: src.Name,") {
		t.Error("missing direct field Name mapping")
	}

	assertCompiles(t, dir)
}

func TestIntegration_IncompatibleTypesUnmapped(t *testing.T) {
	dir := testdataDir("incompatible")
	out := "mapper_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "Source", "-dst", "Dest", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Name (string→string) should be mapped.
	if !strings.Contains(gen, "Name: src.Name,") {
		t.Error("missing Name mapping")
	}
	// Debug (bool→string) is incompatible — should be a TODO comment.
	if !strings.Contains(gen, "// TODO: unmapped field Debug") {
		t.Errorf("expected TODO for incompatible Debug field, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_StrictModeFailsOnUnmapped(t *testing.T) {
	dir := testdataDir("basic")

	_, _, err := runGomapper(t, dir, "-src", "UserDTO", "-dst", "User", "-strict")
	if err == nil {
		t.Fatal("expected strict mode to fail when destination has unmapped fields")
	}
}

func TestIntegration_InvalidModeRejected(t *testing.T) {
	dir := testdataDir("basic")

	_, _, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-mode", "invalid")
	if err == nil {
		t.Fatal("expected error for invalid mode")
	}
}

func TestIntegration_MissingTypeErrors(t *testing.T) {
	dir := testdataDir("basic")

	_, _, err := runGomapper(t, dir, "-src", "NonExistent", "-dst", "UserDTO")
	if err == nil {
		t.Fatal("expected error for non-existent source type")
	}

	_, _, err = runGomapper(t, dir, "-src", "User", "-dst", "NonExistent")
	if err == nil {
		t.Fatal("expected error for non-existent destination type")
	}
}

func TestIntegration_NoFlagsShowsUsage(t *testing.T) {
	dir := testdataDir("basic")

	_, stderr, err := runGomapper(t, dir)
	if err == nil {
		t.Fatal("expected error with no flags")
	}
	if !strings.Contains(stderr, "usage:") {
		t.Errorf("expected usage message, got: %s", stderr)
	}
}

func TestIntegration_VerboseOutput(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_verbose_gen.go"
	defer cleanGenerated(dir, out)

	stdout, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-v", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	combined := stdout + stderr
	if !strings.Contains(combined, "wrote "+out) {
		t.Errorf("verbose mode should print output file name, got: %s", combined)
	}
}

func TestIntegration_ExpectedOutputMatch(t *testing.T) {
	dir := testdataDir("basic")
	out := "mapper_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "User", "-dst", "UserDTO", "-mode", "register", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)
	expected, err := os.ReadFile(filepath.Join(dir, "expected_gen.go.golden"))
	if err != nil {
		t.Fatalf("reading expected output: %v", err)
	}

	if gen != string(expected) {
		t.Errorf("generated output does not match expected.\n--- generated ---\n%s\n--- expected ---\n%s", gen, expected)
	}
}

// --- Phase 2 integration tests ---

func TestIntegration_MapDashSkip(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_skip_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "SkipSrc", "-dst", "SkipDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Name should be mapped.
	if !strings.Contains(gen, "Name: src.Name,") {
		t.Error("missing Name mapping")
	}
	// Secret should NOT appear as a source accessor (map:"-" on SkipSrc.Secret).
	// SkipDst.Secret should be unmapped because SkipSrc.Secret is skipped.
	if !strings.Contains(gen, "// TODO: unmapped field Secret") {
		t.Errorf("expected TODO for unmapped Secret (src has map:\"-\"), got:\n%s", gen)
	}
	// Internal on dst has map:"-" → should not appear at all (no mapping, no TODO).
	if strings.Contains(gen, "Internal") {
		t.Errorf("Internal should be completely skipped (dst map:\"-\"), got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_PointerDeref(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_ptr_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "PtrSrc", "-dst", "PtrDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// *string → string: deref
	if !containsNormalized(gen, "Name: *src.Name,") {
		t.Errorf("expected *src.Name deref, got:\n%s", gen)
	}
	// *int → int64: deref + convert
	if !containsNormalized(gen, "Age: int64(*src.Age),") {
		t.Errorf("expected int64(*src.Age) deref+convert, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_PointerAddrOf(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_addr_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "AddrSrc", "-dst", "AddrDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// string → *string: addr-of
	if !containsNormalized(gen, "Name: &src.Name,") {
		t.Errorf("expected &src.Name addr-of, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_SliceFieldsFuncMode(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_slice_gen.go"
	defer cleanGenerated(dir, out)

	// Generate both pairs so MapItemToItemDTO exists for the inline loop.
	_, stderr, err := runGomapper(t, dir, "-pairs", "Item:ItemDTO,SliceSrc:SliceDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Title should be a direct mapping.
	if !containsNormalized(gen, "Title: src.Title,") {
		t.Errorf("expected direct Title mapping, got:\n%s", gen)
	}
	// Should generate inline loop, NOT mapper.MapSlice.
	if strings.Contains(gen, "mapper.MapSlice") {
		t.Error("func mode should not use mapper.MapSlice")
	}
	if strings.Contains(gen, `import "github.com/KARTIKrocks/mapper"`) {
		t.Error("func mode should not import mapper")
	}
	if !strings.Contains(gen, "_Items := make([]ItemDTO, len(src.Items))") {
		t.Errorf("expected inline slice make, got:\n%s", gen)
	}
	if !strings.Contains(gen, "MapItemToItemDTO(_v)") {
		t.Errorf("expected inline call to MapItemToItemDTO, got:\n%s", gen)
	}
	if !strings.Contains(gen, "Items: _Items,") {
		t.Errorf("expected _Items variable reference in struct literal, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_SliceFieldsRegisterMode(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_slice_reg_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "SliceSrc", "-dst", "SliceDst", "-mode", "register", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Register mode should use mapper.MapSlice.
	if !strings.Contains(gen, "mapper.MapSlice[Item, ItemDTO](src.Items)") {
		t.Errorf("expected mapper.MapSlice call, got:\n%s", gen)
	}
	if !strings.Contains(gen, `import "github.com/KARTIKrocks/mapper"`) {
		t.Errorf("expected mapper import, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_NestedStructFuncMode(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_nested_struct_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-pairs", "Address:AddressDTO,Order:OrderDTO", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Should call MapAddressToAddressDTO for the nested struct.
	if !containsNormalized(gen, "Addr: MapAddressToAddressDTO(src.Addr),") {
		t.Errorf("expected nested struct func call, got:\n%s", gen)
	}
	// Should NOT import mapper.
	if strings.Contains(gen, `import "github.com/KARTIKrocks/mapper"`) {
		t.Error("func mode should not import mapper")
	}

	assertCompiles(t, dir)
}

func TestIntegration_NestedStructRegisterMode(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_nested_struct_reg_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-pairs", "Address:AddressDTO,Order:OrderDTO", "-mode", "register", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Register mode should use mapper.Map[AddressDTO].
	if !strings.Contains(gen, "mapper.Map[AddressDTO](src.Addr)") {
		t.Errorf("expected mapper.Map[AddressDTO] call, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_CaseInsensitiveMatching(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_ci_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "CISrc", "-dst", "CIDst", "-ci", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// UserName → Username and EMail → Email via case-insensitive matching.
	if !containsNormalized(gen, "Username: src.UserName,") {
		t.Errorf("expected UserName→Username CI mapping, got:\n%s", gen)
	}
	if !containsNormalized(gen, "Email: src.EMail,") {
		t.Errorf("expected EMail→Email CI mapping, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_CaseInsensitiveOff(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_ci_off_gen.go"
	defer cleanGenerated(dir, out)

	// Without -ci, UserName and Username should NOT match.
	_, stderr, err := runGomapper(t, dir, "-src", "CISrc", "-dst", "CIDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Both fields should be unmapped.
	if !strings.Contains(gen, "// TODO: unmapped field Username") {
		t.Errorf("expected Username unmapped without -ci, got:\n%s", gen)
	}
	if !strings.Contains(gen, "// TODO: unmapped field Email") {
		t.Errorf("expected Email unmapped without -ci, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_NilSafeDeref(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_nilsafe_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "PtrSrc", "-dst", "PtrDst", "-nil-safe", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Should have nil-safe variable declarations and nil checks.
	if !strings.Contains(gen, "var _Name string") {
		t.Errorf("expected nil-safe var _Name, got:\n%s", gen)
	}
	if !strings.Contains(gen, "if src.Name != nil {") {
		t.Errorf("expected nil check for Name, got:\n%s", gen)
	}
	if !containsNormalized(gen, "Name: _Name,") {
		t.Errorf("expected local var reference _Name, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_NilSafeRegisterMode(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_nilsafe_reg_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "PtrSrc", "-dst", "PtrDst", "-nil-safe", "-mode", "register", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	if !strings.Contains(gen, "var _Name string") {
		t.Errorf("expected nil-safe var _Name in register mode, got:\n%s", gen)
	}
	if !strings.Contains(gen, "if src.Name != nil {") {
		t.Errorf("expected nil check in register mode, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_WithoutNilSafeUnchanged(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_no_nilsafe_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "PtrSrc", "-dst", "PtrDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	// Without -nil-safe, should use bare deref.
	if !containsNormalized(gen, "Name: *src.Name,") {
		t.Errorf("expected bare deref *src.Name, got:\n%s", gen)
	}
	if strings.Contains(gen, "var _Name") {
		t.Errorf("should NOT have nil-safe var without flag, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_FuncModeNeverImportsMapper(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_func_noimport_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-src", "AddrSrc", "-dst", "AddrDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)

	if strings.Contains(gen, `import "github.com/KARTIKrocks/mapper"`) {
		t.Errorf("func mode should never import mapper, got:\n%s", gen)
	}

	assertCompiles(t, dir)
}

func TestIntegration_AdvancedExpectedOutputMatch(t *testing.T) {
	dir := testdataDir("advanced")
	out := "mapper_gen.go"
	defer cleanGenerated(dir, out)

	_, stderr, err := runGomapper(t, dir, "-pairs", "Item:ItemDTO,SliceSrc:SliceDst", "-output", out)
	if err != nil {
		t.Fatalf("gomapper failed: %s", stderr)
	}

	gen := readGenerated(t, dir, out)
	expected, err := os.ReadFile(filepath.Join(dir, "expected_gen.go.golden"))
	if err != nil {
		t.Fatalf("reading expected output: %v", err)
	}

	// Strip the //go:build ignore line used to exclude the golden file from compilation.
	want := strings.TrimPrefix(string(expected), "//go:build ignore\n\n")

	if gen != want {
		t.Errorf("generated output does not match expected.\n--- generated ---\n%s\n--- expected ---\n%s", gen, want)
	}
}
