//go:build ignore

// Code generated by gomapper; DO NOT EDIT.

package advanced

func MapItemToItemDTO(src Item) ItemDTO {
	return ItemDTO{
		ID:   src.ID,
		Name: src.Name,
	}
}

func MapSliceSrcToSliceDst(src SliceSrc) SliceDst {
	_Items := make([]ItemDTO, len(src.Items))
	for _i, _v := range src.Items {
		_Items[_i] = MapItemToItemDTO(_v)
	}
	return SliceDst{
		Title: src.Title,
		Items: _Items,
	}
}
