package generator

import (
	"strings"
	"testing"

	"github.com/KARTIKrocks/gomapper/internal/matcher"
)

func TestGenerate_RegisterMode(t *testing.T) {
	data := Data{
		PkgName: "mypackage",
		Pairs: []PairData{
			{
				SrcType: "User",
				DstType: "UserDTO",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "ID", DstField: "ID"},
					{SrcAccessor: "Name", DstField: "Name"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	// Check essential parts of the output.
	mustContain(t, src, "// Code generated by gomapper; DO NOT EDIT.")
	mustContain(t, src, "package mypackage")
	mustContain(t, src, `import "github.com/KARTIKrocks/mapper"`)
	mustContain(t, src, "mapper.Register(func(src User) UserDTO {")
	mustContain(t, src, "ID:   src.ID,")
	mustContain(t, src, "Name: src.Name,")
}

func TestGenerate_FuncMode(t *testing.T) {
	data := Data{
		PkgName: "mypackage",
		Pairs: []PairData{
			{
				SrcType: "User",
				DstType: "UserDTO",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "ID", DstField: "ID"},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustContain(t, src, "func MapUserToUserDTO(src User) UserDTO {")
	mustNotContain(t, src, "mapper.Register")
}

func TestGenerate_BothMode(t *testing.T) {
	data := Data{
		PkgName: "mypackage",
		Pairs: []PairData{
			{
				SrcType: "User",
				DstType: "UserDTO",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "ID", DstField: "ID"},
				},
			},
		},
	}

	out, err := Generate(data, ModeBoth)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustContain(t, src, "func MapUserToUserDTO(src User) UserDTO {")
	mustContain(t, src, "mapper.Register(MapUserToUserDTO)")
}

func TestGenerate_WithConversion(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Age", DstField: "Age", NeedsConv: true, ConvType: "int64"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "Age: int64(src.Age),")
}

func TestGenerate_WithUnmapped(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType:  "A",
				DstType:  "B",
				Mappings: []matcher.FieldMapping{},
				Unmapped: []matcher.UnmappedField{
					{Name: "Missing", Type: "string"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "// TODO: unmapped field Missing (string)")
}

func TestGenerate_MultiplePairs(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType:  "A",
				DstType:  "B",
				Mappings: []matcher.FieldMapping{{SrcAccessor: "X", DstField: "X"}},
			},
			{
				SrcType:  "C",
				DstType:  "D",
				Mappings: []matcher.FieldMapping{{SrcAccessor: "Y", DstField: "Y"}},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)
	mustContain(t, src, "func(src A) B {")
	mustContain(t, src, "func(src C) D {")
}

func mustContain(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Errorf("output missing %q\n\nfull output:\n%s", substr, s)
	}
}

func mustNotContain(t *testing.T, s, substr string) {
	t.Helper()
	if strings.Contains(s, substr) {
		t.Errorf("output should not contain %q\n\nfull output:\n%s", substr, s)
	}
}

func TestGenerate_Deref(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Name", DstField: "Name", Deref: true},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "*src.Name")
}

func TestGenerate_AddrOf(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Name", DstField: "Name", AddrOf: true},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "&src.Name")
}

func TestGenerate_DerefConvert(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Age", DstField: "Age", Deref: true, NeedsConv: true, ConvType: "int64"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "int64(*src.Age)")
}

func TestGenerate_SliceMap(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceSrc: "Item", SliceDst: "ItemDTO"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "mapper.MapSlice[Item, ItemDTO](src.Items)")
}

func TestGenerate_FuncModeNoMapperImport(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType:  "A",
				DstType:  "B",
				Mappings: []matcher.FieldMapping{{SrcAccessor: "X", DstField: "X"}},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	mustNotContain(t, string(out), `import "github.com/KARTIKrocks/mapper"`)
}

func TestGenerate_FuncModeInlineSlice(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Name", DstField: "Name"},
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceSrc: "Item", SliceDst: "ItemDTO"},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	// func mode should never import mapper.
	mustNotContain(t, src, `import "github.com/KARTIKrocks/mapper"`)
	mustNotContain(t, src, "mapper.MapSlice")

	// Should generate inline loop.
	mustContain(t, src, "_Items := make([]ItemDTO, len(src.Items))")
	mustContain(t, src, "MapItemToItemDTO(_v)")

	// Struct literal should reference the local variable.
	mustContain(t, src, "Items: _Items,")
}

func TestGenerate_RegisterModeSliceUsesMapper(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceSrc: "Item", SliceDst: "ItemDTO"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(out), "mapper.MapSlice[Item, ItemDTO](src.Items)")
}

func TestGenerate_StructMapFuncMode(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "Order",
				DstType: "OrderDTO",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "ID", DstField: "ID"},
					{SrcAccessor: "Addr", DstField: "Addr", IsStructMap: true, StructSrc: "Address", StructDst: "AddressDTO"},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustContain(t, src, "MapAddressToAddressDTO(src.Addr)")
	mustNotContain(t, src, "mapper.Map")
}

func TestGenerate_StructMapRegisterMode(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "Order",
				DstType: "OrderDTO",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Addr", DstField: "Addr", IsStructMap: true, StructSrc: "Address", StructDst: "AddressDTO"},
				},
			},
		},
	}

	out, err := Generate(data, ModeRegister)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustContain(t, src, "mapper.Map[AddressDTO](src.Addr)")
}

func TestGenerate_NilSafeDeref(t *testing.T) {
	for _, mode := range []Mode{ModeRegister, ModeFunc, ModeBoth} {
		t.Run(string(mode), func(t *testing.T) {
			data := Data{
				PkgName: "pkg",
				NilSafe: true,
				Pairs: []PairData{
					{
						SrcType: "A",
						DstType: "B",
						Mappings: []matcher.FieldMapping{
							{SrcAccessor: "Name", DstField: "Name", Deref: true, DstTypeName: "string"},
						},
					},
				},
			}

			out, err := Generate(data, mode)
			if err != nil {
				t.Fatal(err)
			}
			src := string(out)

			// Should have var declaration.
			mustContain(t, src, "var _Name string")
			// Should have nil check.
			mustContain(t, src, "if src.Name != nil {")
			// Should assign inside nil check.
			mustContain(t, src, "_Name = *src.Name")
			// Struct literal should reference the local variable.
			mustContain(t, src, "Name: _Name,")
			// Should NOT have bare *src.Name in the struct literal.
			mustNotContain(t, src, "Name: *src.Name,")
		})
	}
}

func TestGenerate_NilSafeDerefConvert(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		NilSafe: true,
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Age", DstField: "Age", Deref: true, NeedsConv: true, ConvType: "int64", DstTypeName: "int64"},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustContain(t, src, "var _Age int64")
	mustContain(t, src, "_Age = int64(*src.Age)")
	mustContain(t, src, "Age: _Age,")
}

func TestGenerate_NilSafeFalseUnchanged(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		NilSafe: false,
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Name", DstField: "Name", Deref: true, DstTypeName: "string"},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	// Without NilSafe, should use bare deref.
	mustContain(t, src, "Name: *src.Name,")
	// Should NOT have nil-safe variable declarations.
	mustNotContain(t, src, "var _Name")
}

func TestGenerate_NilSafeSliceDeref(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		NilSafe: true,
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceDst: "string", SliceDstFull: "string", SliceElemDeref: true},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustContain(t, src, "if _v != nil {")
	mustContain(t, src, "_Items[_i] = *_v")
}

func TestGenerate_NilSafeSliceDerefStruct(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		NilSafe: true,
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceSrc: "X", SliceDst: "Y", SliceDstFull: "*Y", SliceElemDeref: true, SliceElemAddrOf: true},
				},
			},
		},
	}

	for _, mode := range []Mode{ModeFunc, ModeRegister} {
		t.Run(string(mode), func(t *testing.T) {
			out, err := Generate(data, mode)
			if err != nil {
				t.Fatal(err)
			}
			src := string(out)

			mustContain(t, src, "if _v != nil {")
			mustContain(t, src, "_Items[_i] = &_mapped")
		})
	}
}

func TestGenerate_NoNilSafeSliceDeref(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		NilSafe: false,
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceDst: "string", SliceDstFull: "string", SliceElemDeref: true},
				},
			},
		},
	}

	out, err := Generate(data, ModeFunc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	mustNotContain(t, src, "if _v != nil {")
	mustContain(t, src, "_Items[_i] = *_v")
}

func TestGenerate_BothModeInlineSlice(t *testing.T) {
	data := Data{
		PkgName: "pkg",
		Pairs: []PairData{
			{
				SrcType: "A",
				DstType: "B",
				Mappings: []matcher.FieldMapping{
					{SrcAccessor: "Items", DstField: "Items", IsSliceMap: true, SliceSrc: "Item", SliceDst: "ItemDTO"},
				},
			},
		},
	}

	out, err := Generate(data, ModeBoth)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out)

	// both mode uses inline loops (named function) + register.
	mustContain(t, src, "_Items := make([]ItemDTO, len(src.Items))")
	mustContain(t, src, "Items: _Items,")
	mustContain(t, src, "mapper.Register(MapAToB)")
}
